<table class="table table-condensed report">
<tbody> 
   
   <?php foreach ($lines as $line): ?>
   <?php $uid = sprintf('accordion-%s', md5(uniqid())); ?>

   <tr class="<?= $this->escapeHtml($line->getStatusClass()) == 'ok' ? 'success' : $this->escapeHtml($line->getStatusClass()) ?>">
     <td class="toggle">
        <div class="accordion-group">
          <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" href="#<?=$uid?>">
              <i class="plus icon-plus"></i>
            </a>
          </div>
        </div>
      </td>
      <td class="line-name"><?=$this->escapeHtml($line->getName())?></td>
      <td class="actual"><?=$this->escapeHtml($line->getLastMainMetric())?></td>
      <td class="target"><?=$this->escapeHtml($line->getLastTargetProductivity())?></td>
      <td class="update"><? if($line->isUpdateMoreThanXHours(2)): ?><i class="plus icon-time"></i><? endif; ?></td>
    </tr>
    <tr class="collapsible-details">
      <td colspan="5">
        <div id="<?=$uid?>" class="accordion-body collapse">
          <div class="accordion-inner">

           
            <table id="secondary-metrics" class="mobile-report">
			  <thead> 
			    <tr>
				  <th class="value"><i class="icon-tag icon-large"></i></th>
				  <th class="value"><i class="icon-group icon-large"></i></th>
				  <th class="value-no-icon">V</th> <!-- There are no font awesome icon for speed, therefore we use V that is the first letter for Vitesse which is speed in french. -->
			    </tr>
			  </thead>
		
			  <tbody>
				  <tr>
				    <td class="value-label"><?=$this->escapeHtml($line->getLastProductName())?></td>
				    <td class="value-label"><?=$this->escapeHtml($line->getLastEmployees())?></td>
				    <td class="value-label"><?=$this->escapeHtml($line->getLastReading() ? $line->getLastReading()->getReading() : "N/A")?></td>
				  </tr>
			  </tbody>
		    </table>
		     <div class="last-update"> 
              <p><?=$this->escapeHtml($line->getLastNotes())?></p>
              <p><?=$line->getLastUpdateTime('m/d/Y H:i'); ?></p>
            </div>
		    
          
          </div>
        </div>
      </td>
    </tr>
   <?php endforeach; ?>
</tbody>
</table>
