      <?php foreach ($this->sources as $child): ?>
        <?php if (isset($child->modal_messages) && count($child->modal_messages)): ?>
<div class="modal hide fade modal-alert">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3><?=$child->modal_messages_title?></h3>
  </div>
  <div class="modal-body">
          <?php foreach ($child->modal_messages as $message): ?>
            <p><?=$message;?></p>
          <?php endforeach; ?>
  </div>
  <div class="modal-footer">
    <a href="#" data-dismiss="modal" class="btn">Close</a>
  </div>
</div>
        <?php endif; ?>
      <?php endforeach; ?>
