<div id="layout-navbar" class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar " data-toggle="collapse" data-target=".nav-collapse"></a>
      <a class="brand" href="<?php echo $this->url('home') ?>">Viandes Lacroix</a>
      <div class="nav-collapse collapse">
      <?= $this->navbar_mobile()->render() ?>
      </div>
    </div>
  </div>
</div><!--#layout-navbar-->