<?php foreach ($lines as $line): ?>
<div class="line-container"><div class="line <?=$this->escapeHtml($line->getStatusClass())?>" data-line-reading="<?=$this->escapeHtml($line->getLastReading() ? $line->getLastReading()->getReading() : "")?>" data-line-notes="<?=$this->escapeHtml($line->getLastNotes())?>" data-line-employee="<?=$this->escapeHtml($line->getLastEmployees())?>" data-line-name="<?=$this->escapeHtml($line->getName())?>" data-line-id="<?=$this->escapeHtml($line->getId())?>" data-product-id="<?=$this->escapeHtml($line->getLastProductId())?>">
   <div class="stars">
     <?php for ($i = 0; $i < $line->getLastStars(); $i++): ?>
     <i class="icon-star"></i>
     <?php endfor; ?>
   </div>

   <div class="name"><?=$this->escapeHtml($line->getName())?></div>
   <hr>
   <h4 class="title-main-metric"><?=$this->escapeHtml($this->translate('Kebab / Pers. / Hour'));?></h4>
   <table id="main-metrics" class="">
     <thead>
       <tr>
         <th class="value">
           <?=$this->escapeHtml($line->getLastMainMetric())?>
         </th>
         <th class="value"><?=$this->escapeHtml($line->getLastTargetProductivity())?></th>
       </tr>
     </thead>

     <tbody>
         <tr>
           <td class="value-label">
             <?=$this->escapeHtml($this->translate('Actual'));?>
             <?php if ($line->getLastNotes()): ?>
               <i class="icon-comment comments-popover" data-placement="bottom" data-toggle="popover"  data-content="<?=$this->escapeHtml($line->getLastNotes())?>" title="Notes"></i>
             <?php endif; ?>
           </td>
           <td class="value-label"><?=$this->escapeHtml($this->translate('Target'));?></td>
         </tr>
     </tbody>
   </table>

   <table id="secondary-metrics" class="">
	 <tr>
       <th class="value product" rowspan="2"><?=$this->escapeHtml($line->getLastProductName())?></th>
       <th class="value"><i class="icon-group icon-large"></i></th>
       <th class="value-no-icon">V</th> <!-- There are no font awesome icon for speed, therefore we use V that is the first letter for Vitesse which is speed in french. -->
     </tr>
     <tr>
       <td class="value-label"><?=$this->escapeHtml($line->getLastEmployees())?></td>
       <td class="value-label"><?=$this->escapeHtml($line->getLastReading() ? $line->getLastReading()->getReading() : "N/A")?></td>
     </tr>
   </table>

   <div class="controls">
     <a href="#reading-modal" role="button" class="btn-add btn btn-small" data-toggle="modal"><?=$this->escapeHtml($this->translate('Add reading'))?></a>
     <a href="#speed-modal-<?=$this->escapeHtml($line->getId())?>" role="button" class="btn-add btn btn-small" data-toggle="modal"><?=$this->escapeHtml($this->translate('Recommendations'))?></a>
   </div>

   <!--
   <div class="extra-info">
   <table id="main-metrics" class="">
     <tbody>
         <tr>
           <td class="team-leader">"Mart"</td>
           <td class="last-update"><?=$line->getLastUpdateTime('m/d/Y H:i'); ?></td>
         </tr>
     </tbody>
   </table>
   </div>
   -->

   <div class="extra-info">
     <span class="team-leader">
       "mart"
     </span>
     <span class="last-update  <?= $line->isUpdateMoreThanXHours(2) ? 'bad' : '' ?>" >
       <?=$line->getLastUpdateTime('m/d/Y H:i'); ?>
     </span>
   </div>

   <div id="speed-modal-<?=$this->escapeHtml($line->getId())?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="reading-modal-label" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 id="reading-modal-label"><?=$this->escapeHtml($this->translate('Proposition to increase')); ?></h3>
  </div>
  <div class="modal-body">
     <div class="options-container">
	   <?php if ($line->getProductivityOptions()): ?>
	   <table class="table table-striped">
		 <thead>
		   <tr>
			 <th><?=$this->escapeHtml($this->translate('Speed'))?></th>
			 <th><?=$this->escapeHtml($this->translate('Kebab / Pers. / Hour'))?></th>
		   </tr>
		 </thead>

		 <tbody>
		   <?php foreach ($line->getProductivityOptions() as $option): ?>
			 <tr>
			   <td><?=$this->escapeHtml($option['motor']);?></td>
			   <td><?=$this->escapeHtml($option['result']);?></td>
			 </tr>
		   <?php endforeach; ?>
		 </tbody>
	   </table>
	   <?php endif; ?>
	</div>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

</div></div>
<?php endforeach; ?>

<div id="reading-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="reading-modal-label" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 id="reading-modal-label"><?=$this->escapeHtml($this->translate('Add a new reading')); ?></h3>
  </div>
  <div class="modal-body">
    <?=$this->bootstrap()->form($reading_form)?>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary btn-save">Save changes</button>
  </div>
</div>
