CREATE TABLE people (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(200) NOT NULL,
  last_name VARCHAR(200) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE users (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(250) NOT NULL,
  password CHAR(32) NOT NULL,
  salt CHAR(32) NOT NULL,
  person_id INTEGER DEFAULT NULL,

  UNIQUE KEY email (email)
) ENGINE=InnoDB;

CREATE TABLE user_roles (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,  
  user_id INTEGER NOT NULL,
  role CHAR(32) NOT NULL,
  UNIQUE KEY (user_id, role)
) ENGINE=InnoDB;

ALTER TABLE user_roles ADD FOREIGN KEY fk_user (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE;
